name: quality_control
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.13
  - annotated-types=0.7.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.14
  - cairo=1.18.2
  - certifi=2024.12.14
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - click=8.1.8
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - colormath=3.0.0
  - expat=2.6.4
  - fastqc=0.12.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - giflib=5.2.2
  - graphite2=1.3.13
  - h2=4.1.0
  - harfbuzz=10.2.0
  - hpack=4.0.0
  - humanfriendly=10.0
  - humanize=4.11.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - jinja2=3.1.5
  - kaleido-core=0.2.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libdeflate=1.23
  - libedit=3.1.20240808
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.82.2
  - libgomp=14.2.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblzma=5.6.3
  - libmpdec=4.0.0
  - libopenblas=0.3.28
  - libpng=1.6.45
  - libsqlite=3.47.2
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.7.0
  - libuuid=2.38.1
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mathjax=2.7.7
  - mdurl=0.1.2
  - multiqc=1.25.2
  - nanoq=0.9.0
  - natsort=8.4.0
  - ncurses=6.5
  - networkx=3.4.2
  - nspr=4.36
  - nss=3.107
  - numpy=2.2.1
  - openjdk=23.0.1
  - openjpeg=2.5.3
  - openssl=3.4.0
  - packaging=24.2
  - pcre2=10.44
  - perl=5.32.1
  - pillow=11.1.0
  - pip=24.3.1
  - pixman=0.44.2
  - plotly=5.24.1
  - pthread-stubs=0.4
  - pyaml-env=1.2.2
  - pycparser=2.22
  - pydantic=2.10.5
  - pydantic-core=2.27.2
  - pygments=2.19.1
  - pysocks=1.7.1
  - python=3.13.1
  - python-kaleido=0.2.1
  - python_abi=3.13
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - rich=13.9.4
  - rich-click=1.8.5
  - spectra=0.0.11
  - sqlite=3.47.2
  - tenacity=9.0.0
  - tk=8.6.13
  - tqdm=4.67.1
  - typeguard=4.4.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - urllib3=2.3.0
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.10
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - yaml=0.2.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.6
